# NumPy Foundations – Core Concepts

## What is NumPy?
**NumPy (Numerical Python)** is the fundamental library for numerical computing in Python. It provides the powerful **ndarray (N-dimensional array)** object and fast mathematical operations.

---

## Why does NumPy exist?
Python lists are flexible but slow for large-scale numerical computation because each element is a separate Python object.

NumPy solves this by:
- Storing elements in **continuous memory**
- Using the **same data type** for all elements
- Performing calculations in optimized C code
- Supporting **vectorized operations** (no explicit Python loops)

This makes NumPy the foundation of AI, Machine Learning, Data Science, Scientific Computing, and Computer Vision.

---

## Python List vs NumPy Array

### Python List
- Can store different data types.
- Slower for mathematical operations.
- Uses more memory.

### NumPy Array
- Stores one common data type.
- Faster and more memory efficient.
- Designed for mathematical computation.

---

## What is an Array?
An array is a collection of similar values stored in **continuous memory**.

Example:
[10, 20, 30, 40]

---

## Dimensions
- **1D Array** → One row of values.
- **2D Array** → Rows and columns (table/matrix).
- **3D Array** → Multiple 2D arrays stacked together (image batches, videos, tensors).

---

## Important Properties
### shape
Number of rows and columns.
Example: (2,3)

### size
Total number of elements.

### ndim
Number of dimensions (axes).

### dtype
Data type of elements such as int64 or float64.

---

## Vectorization
Instead of looping through each element, NumPy performs operations on the whole array.

Example:
arr + 10

---

## Broadcasting
Broadcasting automatically expands compatible arrays during arithmetic.

Example:
[1,2,3] + 5
becomes
[6,7,8]

---

## Why is NumPy important for AI/ML?
Nearly every AI library (TensorFlow, PyTorch, Pandas, SciPy, scikit-learn, OpenCV) depends on NumPy because machine learning is built on matrices, vectors, and numerical computation.

---
## Summary
- NumPy is the standard numerical computing library.
- Arrays are faster than Python lists.
- Continuous memory improves performance.
- Learn shape, size, ndim, dtype, vectorization, and broadcasting before moving ahead.


In [ ]:
import numpy as np
print('NumPy Version:', np.__version__)

In [ ]:
# 1D, 2D and 3D arrays
arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr1) ; print(arr2) ; print(arr3)

In [ ]:
for name,arr in [('1D',arr1),('2D',arr2),('3D',arr3)]:
    print(name)
    print('shape:',arr.shape)
    print('size:',arr.size)
    print('ndim:',arr.ndim)
    print('dtype:',arr.dtype)
    print()

In [ ]:
arr=np.array([1,2,3])
print('Vectorization:',arr*5)
print('Broadcasting:',arr+10)

## Practice Questions
1. Why is NumPy faster?
2. Explain shape, size, ndim and dtype.
3. Difference between Python list and NumPy array.
4. Create a 3x3 array and print its properties.

In [3]:
# Code Practice

import numpy as np

arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])
print("shape : ", arr.shape)
print("Size :", arr.size)
print("Type : ", arr.dtype)
print("Dimension : ", arr.ndim)

shape :  (7,)
Size : 7
Type :  int64
Dimension :  1


In [14]:
# 2D array:

arr = np.array([[1,2,3],[2,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [2 5 6]]
2


In [19]:
# 3D array:

arr = np.array([[
    [1,2,3],
    [2,5,6],
    [34,5,6]],

    [
        [1,3,5],
        [2,3,4],
        [5,7,89]
    ]])

print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 2  5  6]
  [34  5  6]]

 [[ 1  3  5]
  [ 2  3  4]
  [ 5  7 89]]]
3


In [24]:
# Victorization:

arr = np.array([1,2,3,4,5])
print(arr + 15)
print(arr - 5)
print(arr * 100)
print(arr / 2)


[16 17 18 19 20]
[-4 -3 -2 -1  0]
[100 200 300 400 500]
[0.5 1.  1.5 2.  2.5]


In [22]:
import numpy as np

list1 = [1,2,3]

array1 = np.array([1,2,3])

print(type(list1))
print(type(array1))

<class 'list'>
<class 'numpy.ndarray'>


In [25]:
arr = np.array([1,2,3,4])

print(arr.itemsize)

print(arr.nbytes)


8
32


In [26]:
marks = np.array([65,70,80,90,75])
print(marks + 5)

[70 75 85 95 80]


In [27]:
salary = np.array([25000,30000,40000,50000])
print(salary * 1.10)

[27500. 33000. 44000. 55000.]
