# Task 3: NumPy Advanced Operations – Core Concepts

This notebook covers the theory and practice needed for AI/ML preprocessing.

# Topics
1. Indexing
2. Slicing
3. Broadcasting (Advanced)
4. Vectorization (Advanced)
5. Universal Functions (ufuncs)
6. Boolean Masking
7. Performance Comparison


## 1. Indexing
Indexing accesses specific elements.
- 1D: arr[0]
- 2D: arr[row, col]
- 3D: arr[layer, row, col]
- Negative indexing: arr[-1]
- Fancy indexing and Boolean indexing.

In [8]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0,1])
print(arr[:,1])
print(arr[[0,2]])


20
[20 50 80]
[[10 20 30]
 [70 80 90]]


## 2. Slicing
Syntax: arr[start:stop:step]
For 2D: arr[rows, cols]

In [9]:
print(arr[0:2,1:3])
print(arr[::-1])


[[20 30]
 [50 60]]
[[70 80 90]
 [40 50 60]
 [10 20 30]]


## 3. Broadcasting
Broadcasting automatically expands compatible shapes during arithmetic.

In [10]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
print(a+b)


[[11 22 33]
 [14 25 36]]


## 4. Vectorization
Operate on entire arrays without Python loops.

In [13]:
x=np.array([1,2,3,4])
print(x*5)
print(x**2)


[ 5 10 15 20]
[ 1  4  9 16]


## 5. Universal Functions (ufuncs)

In [ ]:
print(np.sqrt(x))
print(np.square(x))
print(np.mean(x))
print(np.max(x))


## 6. Boolean Masking
Filter arrays using conditions.

In [14]:
marks=np.array([45,67,82,91,58])
print(marks[marks>=60])


[67 82 91]


## 7. Performance Comparison

In [ ]:
from timeit import timeit
py=timeit("[i*2 for i in range(10000)]",number=100)

np_time=timeit("arr*2",setup="import numpy as np; arr=np.arange(10000)",number=100)
print("Python:",py)
print("NumPy :",np_time)


Python: 0.03941360899989377
NumPy : 0.000989648000086163


## Practice
1. Extract rows and columns.
2. Reverse arrays using slicing.
3. Filter values >50.
4. Use np.sqrt(), np.mean(), np.sum().
5. Compare Python loops with NumPy vectorization.

## Git
`git add .`
`git commit -m "Complete NumPy advanced operations"`

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])

print(arr[0])
print(arr[2])
print(arr[-1])




10
30
40


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 2, 4]])

print(arr[[1,2,3]])

[10 30 50]
[20 30 40]


In [3]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# First row
print(arr[0])

# Second column
print(arr[:, 1])

# Third row
print(arr[2])

[1 2 3]
[2 5 8]
[7 8 9]


In [4]:
# Slicing

arr = np.array([10,20,30,40,50])

print(arr[1:3])

[20 30]


In [6]:
arr = np.array([[1,2,3],[2,3,4]])
print(arr[0:2,1:3])
print(arr +5)

[[2 3]
 [3 4]]
[[6 7 8]
 [7 8 9]]


In [5]:
arr = np.array([10,20,30,40,50])

print(np.sqrt(arr))
print(np.square(arr))
# print(np.power(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.abs(arr))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[ 100  400  900 1600 2500]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
[10 20 30 40 50]


In [7]:
arr = np.array([10,20,30,40,50])
print(arr[arr>20])

[30 40 50]
